#!/bin/bash

sync_gmi() {
  # poll gmi and mbsync
  command -v gmi >/dev/null && GMI=gmi || GMI=~/bin/gmi

  [[ -e ~/.mail/work     ]] && $GMI sync -C ~/.mail/work     &
  [[ -e ~/.mail/personal ]] && $GMI sync -C ~/.mail/personal &
  [[ -e ~/.mail/hotmail  ]] &&    mbsync            hotmail  &
  wait
}

sync_muchsync() {
  if gcertstatus; then
    # nonew very important, avoids infinite recursion
    if ! ssh -O check box; then
      notify-send "need sk touch" "run \`ssh box true\` in a terminal" && return 1
    fi
    muchsync --nonew box
  else
    # some scope-screep, but since this hook runs periodically, it's a good place
    # to remind less frequently about invalid gcert
    if [[ $(($(<~/.cache/last_gcert_invalid_notif) + 3600)) -lt $(date +%s) ]] 2>/dev/null; then
      date +%s >~/.cache/last_gcert_invalid_notif
      notify-send "invalid gcert" "$(gcertstatus 2>&1)"
    fi
  fi
}

# if we are the muchsync server, actually sync. otherwise run muchsync
id=$(muchsync --self)
if [[ $id -eq 7633996751889129249 ]] || [[ $id -eq 6172958386954966993 ]]; then
  sync_gmi
else
  if command -v gcertstatus; then
    sync_muchsync
  else
    muchsync --nonew a
  fi
fi

# rm deleted mail
notmuch search --output=files --format=text0 tag:deleted | xargs -0 rm -f
