# copied the whole default, didn't know which to omit in the smaller list
prompt_order = [
    # moved these two to front
    "directory",
    "time",

    "username",
    "hostname",
    "kubernetes",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "golang",
    "haskell",
    "java",
    "julia",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]

[directory]
truncation_length = 5
fish_style_pwd_dir_length = 2

[jobs]
disabled = true

[python]
disabled = true

[time]
disabled = false
