;; -*- no-byte-compile: t; -*-
(package! solarized-theme)
(package! buffer-move)
(package! zoom-window)
(package! string-inflection)
(package! dired-hide-dotfiles)
(package! pkgbuild-mode)
(package! highlight-thing)
(package! defrepeater)
(package! keychain-environment)
(package! ztree)
(package! notmuch-unread :recipe (:host github :repo "rbutoi/notmuch-unread"))
(package! visual-fill-column)
(package! password-store)
(package! outshine)
(package! mac-pseudo-daemon :disable (not IS-MAC))
(package! ivy-xref)
(package! eglot)
