;;; persistent-geometry.el --- Save frame geometry on restart -*- lexical-binding: t; -*-

;; Author: Gemini
;; Version: 1.3
;; Keywords: frames, geometry, convenience

;;; Commentary:

;; This package provides a single command to save the main frame's
;; position, dimensions, and fullscreen state upon exiting Emacs.
;;
;; Note: Restoration is handled via `early-init.el` to prevent visual
;; jumping during startup.

;;; Code:

(require 'pp)

(defgroup persistent-geometry nil
  "Save frame geometry."
  :group 'frames)

(defcustom persistent-geometry-file (locate-user-emacs-file "var/frame-geometry.el")
  "File used to save the frame geometry parameters."
  :type 'file
  :group 'persistent-geometry)

(defun persistent-geometry--get-params ()
  "Extract specific geometry parameters from the selected frame."
  (let ((params (frame-parameters)))
    (mapcar (lambda (prop)
              (cons prop (cdr (assq prop params))))
            '(left top width height fullscreen))))

;;;###autoload
(defun persistent-geometry-save ()
  "Save the current frame's geometry to `persistent-geometry-file`."
  (interactive)
  (make-directory (file-name-directory persistent-geometry-file) t)
  (with-temp-file persistent-geometry-file
    (insert ";; Auto-generated Emacs frame geometry.\n")
    (insert ";; Do not edit this file manually unless you know what you are doing.\n\n")
    (pp (persistent-geometry--get-params) (current-buffer))))

(provide 'persistent-geometry)
;;; persistent-geometry.el ends here
