#!/bin/sh

# sort emails into appropriate account tag
notmuch tag +work     -- tag:new path:work/**
notmuch tag +personal -- tag:new path:personal/**
notmuch tag +hotmail  -- tag:new path:hotmail/**

# mbsync doesn't do any notmuch tagging, just maildir syncing
notmuch tag +inbox    -- tag:new path:hotmail/Inbox/**
notmuch tag +sent     -- tag:new path:hotmail/Sent/**
notmuch tag +draft    -- tag:new path:hotmail/Drafts/**

# since the "primary" is represented by a lack of a category tag, give it a tag
# to make it easier
notmuch tag +primary  -- tag:new and tag:personal and \
  not tag:social                                  and \
  not tag:promotions                              and \
  not tag:updates                                 and \
  not tag:forums

# remove new tag
notmuch tag -new      -- tag:new

# all of real filtering and tagging is done by Gmail, so they are accessible
# from the web, mobile, etc

################################################################################
# notify new mail
if pgrep '^sway$' >/dev/null; then
  # don't notify in emacs, not needed when looking
  export SWAYSOCK=$(sway --get-socketpath)
  [ "$(swaymsg -t get_tree | jq -r '.. | select(.type?) |
  select(.focused==true).app_id')" == emacs ] ||
    swaymsg exec notify-notmuch

  # update waybar unread count
  pkill -RTMIN+9 waybar
fi
