#!/bin/bash

tag_gmi() {
  # sort emails into appropriate account tag
  notmuch tag +work     -- tag:new path:work/**
  notmuch tag +personal -- tag:new path:personal/**
  notmuch tag +hotmail  -- tag:new path:hotmail/**

  # mbsync doesn't do any notmuch tagging, just maildir syncing
  notmuch tag +inbox    -- tag:new path:hotmail/Inbox/**
  notmuch tag +sent     -- tag:new path:hotmail/Sent/**
  notmuch tag +draft    -- tag:new path:hotmail/Drafts/**

  # since the "primary" is represented by a lack of a category tag, give it a tag
  # to make it easier
  notmuch tag +primary  -- tag:new and tag:personal and \
    not tag:social                                  and \
    not tag:promotions                              and \
    not tag:updates                                 and \
    not tag:forums

  # remove new tag
  notmuch tag -new      -- tag:new

  # all of real filtering and tagging is done by Gmail, so they are accessible
  # from the web, mobile, etc
}

sync_muchsync() {
  # if we're using muchsync, do it one more time to push read messages
  gcertstatus && ssh -O check box &&  # pre hook should have started multiplexing
    muchsync --nonew box ||           # nonew very important, avoids infinite recursion
      exit 1  # fail out so we don't touch unread files, which are also used for
              # mail freshness
}

if [[ $(muchsync --self) == 7633996751889129249 ]]; then
  tag_gmi
else
  sync_muchsync
fi

################################################################################
# notify new mail

if pgrep '^sway$' >/dev/null; then
  # don't notify in emacs, not needed when looking
  export SWAYSOCK=$(sway --get-socketpath)
  [ "$(swaymsg -t get_tree | jq -r '.. | select(.type?) |
  select(.focused==true).app_id')" == emacs ] ||
    swaymsg exec notify-notmuch

  # update waybar unread count
  pkill -RTMIN+9 waybar
fi

# cache unread count in /tmp
DB_PATH=$(notmuch config get database.path)
[ -e $DB_PATH/work ]     && notmuch count 'is:work     and is:inbox and is:unread' > /tmp/mail_unread_count_work     || true
[ -e $DB_PATH/personal ] && notmuch count 'is:personal and is:inbox and is:unread' > /tmp/mail_unread_count_personal || true
[ -e $DB_PATH/hotmail  ] && notmuch count 'is:hotmail  and is:inbox and is:unread' > /tmp/mail_unread_count_hotmail  || true
