#!/bin/bash

DB_PATH=$(notmuch config get database.path)

# log to systemd if not running from systemd service which is already logged
if [[ -n "$IN_NOTMUCH_SYSTEMD" ]]; then
  $DB_PATH/.notmuch/hooks/pre-new-help "$@"
else
  $DB_PATH/.notmuch/hooks/pre-new-help "$@" | tee >(logger -t notmuch-new-adhoc) 2>&1
fi
