#!/bin/sh

ping -c1 imap.gmail.com >/dev/null || exit 1

# poll gmi and mbsync
command -v gmi >/dev/null && GMI=gmi || GMI=~/bin/gmi

[ -e ~/.mail/work ]     && $GMI sync -C ~/.mail/work     &
[ -e ~/.mail/personal ] && $GMI sync -C ~/.mail/personal &
[ -e ~/.mail/hotmail  ] &&    mbsync            hotmail  &
wait

# rm deleted mail
notmuch search --output=files --format=text0 tag:deleted | xargs -0 rm -f
