#!/bin/bash
set -xeuo pipefail

ping -q -c 1 imap.gmail.com 2>&1 >/dev/null # bail without internet

# poll gmi and mbsync
command -v gmi >/dev/null && GMI=gmi || GMI=~/bin/gmi

[ -e ~/.mail/work ]     && $GMI sync -C ~/.mail/work     &
[ -e ~/.mail/personal ] && $GMI sync -C ~/.mail/personal &
[ -e ~/.mail/hotmail  ] &&    mbsync            hotmail  &
wait

# rm deleted mail
notmuch search --output=files --format=text0 tag:deleted | xargs -0 rm -f
