#!/bin/bash
set -xeuo pipefail

# bail without internet, with a single 10s retry
ping -q -c 1 8.8.8.8 2>&1 >/dev/null ||
    (echo "ping check failed, retrying in 10s..." &&
         sleep 10s && ping -q -c 1 8.8.8.8 2>&1 >/dev/null)

# poll gmi and mbsync
command -v gmi >/dev/null && GMI=gmi || GMI=~/bin/gmi

[ -e ~/.mail/work ]     && $GMI sync -C ~/.mail/work     &
[ -e ~/.mail/personal ] && $GMI sync -C ~/.mail/personal &
[ -e ~/.mail/hotmail  ] &&    mbsync            hotmail  &
wait

# rm deleted mail
notmuch search --output=files --format=text0 tag:deleted | xargs -0 rm -f
